In [1]:
import pandas as pd



df = pd.read_csv("IMDB Dataset.csv")


print("--- First 5 Rows ---")
display(df.head())


print("\n--- Descriptive Statistics ---")
display(df.describe())


print("\n--- Dataset Info ---")
df.info()


print("\n--- Sentiment Distribution ---")
print(df['sentiment'].value_counts())

--- First 5 Rows ---

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

--- Descriptive Statistics ---

                                                   review sentiment
count                                               50000     50000
unique                                              49582         2
top     Loved today's show!!! It was a variety and not...  positive
freq                                                    5     25000

--- Dataset Info ---
<class 'pandas.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   review     50000 non-null  str
 1   sentiment  50000 non-null  str
dtypes: str(2)
memory usage: 781.4 KB

--- Sentiment Distribution ---
sentiment
positive    25000
negative    25000
Name: count, dtype: int64